name: 'Create Release'

description: 'Creates a new release on GitHub'

inputs:
  tag_name:
    description: 'The name of the tag associated with this release'
    required: true
    default: ${{ github.ref }}
  name:
    description: 'The name of the release'
    required: true
  prerelease:
    description: 'Indicates if the release is a prerelease'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'index.js'

outputs:
  id:
    description: 'The ID of the created release'
